# -----------------------------
# 1. Build Stage - React build
# -----------------------------
FROM public.ecr.aws/docker/library/node:20 AS builder

WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy all frontend source
COPY . .

# Build React app
RUN npm run build

# -----------------------------
# 2. Run Stage - Nginx server
# -----------------------------
FROM public.ecr.aws/docker/library/nginx:1.27-alpine

# Copy build files to nginx html folder
COPY --from=builder /app/build /usr/share/nginx/html

# Copy custom nginx config (React Router)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 3000
EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
